export class RcvGridConfig {
    public MASTER = [
        { caption: 'uid', dataField: 'uid', width: 300, fixed: true, visible: true, allowEditing: false },
        { caption: 'tenant', dataField: 'tenant', width: 300, fixed: false, visible: true, allowEditing: false },
        { caption: 'companyName', dataField: 'companyName', width: 300, fixed: false, visible: true },
        { caption: 'name', dataField: 'name', width: 300, fixed: false, visible: true },
        { caption: 'ownoranotherflg', dataField: 'ownoranotherflg', width: 300, fixed: false, visible: true },
        { caption: 'transportpriority', dataField: 'transportpriority', width: 300, fixed: false, visible: true },
        { caption: 'ownercustomercd', dataField: 'ownercustomercd', width: 300, fixed: false, visible: true },
        { caption: 'ownersuppliercd', dataField: 'ownersuppliercd', width: 300, fixed: false, visible: true },
        { caption: 'itemadmin', dataField: 'itemadmin', width: 300, fixed: false, visible: true },
        { caption: 'actflg', dataField: 'actflg', width: 300, fixed: false, visible: true },
        { caption: 'companycd', dataField: 'companycd', width: 300, fixed: false, visible: true },
        { caption: 'countrycd', dataField: 'countrycd', width: 300, fixed: false, visible: true },
        { caption: 'postno', dataField: 'postno', width: 300, fixed: false, visible: true },
        { caption: 'districtcd', dataField: 'districtcd', width: 300, fixed: false, visible: true },
        { caption: 'portcd', dataField: 'portcd', width: 300, fixed: false, visible: true },
        { caption: 'refname', dataField: 'refname', width: 300, fixed: false, visible: true },
        { caption: 'address1', dataField: 'address1', width: 300, fixed: false, visible: true },
        { caption: 'address2', dataField: 'address2', width: 300, fixed: false, visible: true },
        { caption: 'address3', dataField: 'address3', width: 300, fixed: false, visible: true },
        { caption: 'f_USER3', dataField: 'f_USER3', width: 300, fixed: false, visible: true },
        { caption: 'f_USER5', dataField: 'f_USER5', width: 300, fixed: false, visible: true },
        { caption: 'companygroup', dataField: 'companygroup', width: 300, fixed: false, visible: true },
        { caption: 'typecustomer', dataField: 'typecustomer', width: 300, fixed: false, visible: true },
        { caption: 'f_USER4', dataField: 'f_USER4', width: 300, fixed: false, visible: true },
        { caption: 'phone1', dataField: 'phone1', width: 300, fixed: false, visible: true },
        { caption: 'phone2', dataField: 'phone2', width: 300, fixed: false, visible: true },
        { caption: 'typesupplier', dataField: 'typesupplier', width: 300, fixed: false, visible: true },
        { caption: 'typeshipto', dataField: 'typeshipto', width: 300, fixed: false, visible: true },
        { caption: 'typecarrier', dataField: 'typecarrier', width: 300, fixed: false, visible: true },
        { caption: 'typeetc', dataField: 'typeetc', width: 300, fixed: false, visible: true },
        { caption: 'typewarehouse', dataField: 'typewarehouse', width: 300, fixed: false, visible: true },
        { caption: 'f_USER1', dataField: 'f_USER1', width: 300, fixed: false, visible: true },
        { caption: 'typeowner', dataField: 'typeowner', width: 300, fixed: false, visible: true },
        { caption: 'f_USER2', dataField: 'f_USER2', width: 300, fixed: false, visible: true },
        { caption: 'f_USER10', dataField: 'f_USER10', width: 300, fixed: false, visible: true },
        { caption: 'purchasetype', dataField: 'purchasetype', width: 300, fixed: false, visible: true },
        { caption: 'ownerrefflg', dataField: 'ownerrefflg', width: 300, fixed: false, visible: true },
        { caption: 'f_USER8', dataField: 'f_USER8', width: 300, fixed: false, visible: true },
        { caption: 'f_USER6', dataField: 'f_USER6', width: 300, fixed: false, visible: true },
        { caption: 'f_USER9', dataField: 'f_USER9', width: 300, fixed: false, visible: true },
        { caption: 'f_USER7', dataField: 'f_USER7', width: 300, fixed: false, visible: true },
        { caption: 'calendarcd', dataField: 'calendarcd', width: 300, fixed: false, visible: true },
        { caption: 'bsnumber', dataField: 'bsnumber', width: 300, fixed: false, visible: true },
        { caption: 'fax1', dataField: 'fax1', width: 300, fixed: false, visible: true },
        { caption: 'email', dataField: 'email', width: 300, fixed: false, visible: true },
        { caption: 'aname', dataField: 'aname', width: 300, fixed: false, visible: true },
        { caption: 'sname', dataField: 'sname', width: 300, fixed: false, visible: true },
        { caption: 'fax2', dataField: 'fax2', width: 300, fixed: false, visible: true },
        { caption: 'CREATEDBY', dataField: 'CREATEDBY', width: 300, fixed: false, visible: true },
        { caption: 'CREATEDDATE', dataField: 'CREATEDDATE', width: 300, fixed: false, visible: true },
        { caption: 'CREATEIP', dataField: 'CREATEIP', width: 300, fixed: false, visible: true },
        { caption: 'LASTMODIFIEDBY', dataField: 'LASTMODIFIEDBY', width: 300, fixed: false, visible: true },
        { caption: 'LASTMODIFIEDDATE', dataField: 'LASTMODIFIEDDATE', width: 300, fixed: false, visible: true },
        { caption: 'LASTMODIFIEDIP', dataField: 'LASTMODIFIEDIP', width: 300, fixed: false, visible: true },
        { caption: 'UTC', dataField: 'UTC', width: 300, fixed: false, visible: true },
        { caption: 'REMARKS', dataField: 'REMARKS', width: 300, fixed: false, visible: true },
        { caption: 'ROW_VERSION', dataField: 'ROW_VERSION', width: 300, fixed: false, visible: true },
        { caption: 'TENANT', dataField: 'TENANT', width: 300, fixed: false, visible: true },
    ];

    public DETAIL = [
        { caption: 'uid', dataField: 'uid', width: 200, fixed: false, visible: true, allowEditing: false },
        { caption: 'tenant', dataField: 'tenant', width: 200, fixed: false, visible: true, allowEditing: false },
        { caption: 'ownercd', dataField: 'ownercd', width: 200, fixed: false, visible: true, allowEditing: true, editCellTemplate: 'SH_PTNRKEY' },
        { caption: 'ownerName', dataField: 'ownerName', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'rcvKey', dataField: 'rcvKey', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'rcvLineNo', dataField: 'rcvLineNo', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'supplierRcvLineNo', dataField: 'supplierRcvLineNo', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'poKey', dataField: 'poKey', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'poLineNo', dataField: 'poLineNo', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'poType', dataField: 'poType', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'ownerPoNo', dataField: 'ownerPoNo', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'ownerPoLineNo', dataField: 'ownerPoLineNo', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'originalPoNo', dataField: 'originalPoNo', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'originalPoLineNo', dataField: 'originalPoLineNo', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'poDate', dataField: 'poDate', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'itemAdmincd', dataField: 'itemAdmincd', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'itemAdminName', dataField: 'itemAdminName', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'itemcd', dataField: 'itemcd', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'itemName', dataField: 'itemName', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'ifItemcd', dataField: 'ifItemcd', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'lot1', dataField: 'lot1', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'lot2', dataField: 'lot2', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'lot3', dataField: 'lot3', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'lot4', dataField: 'lot4', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'lot5', dataField: 'lot5', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'otherLot1', dataField: 'otherLot1', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'otherLot2', dataField: 'otherLot2', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'otherLot3', dataField: 'otherLot3', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'otherLot4', dataField: 'otherLot4', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'otherLot5', dataField: 'otherLot5', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'damageFlg', dataField: 'damageFlg', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'noShippingFlg', dataField: 'noShippingFlg', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'foreignCargoFlg', dataField: 'foreignCargoFlg', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'customsReleaseFlg', dataField: 'customsReleaseFlg', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'taxFlg', dataField: 'taxFlg', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'expectQty1', dataField: 'expectQty1', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'expectQty2', dataField: 'expectQty2', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'expectQty3', dataField: 'expectQty3', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'receivedQty1', dataField: 'receivedQty1', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'receivedQty2', dataField: 'receivedQty2', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'receivedQty3', dataField: 'receivedQty3', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'adjustQty1', dataField: 'adjustQty1', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'adjustQty2', dataField: 'adjustQty2', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'adjustQty3', dataField: 'adjustQty3', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'rcvTagQty1', dataField: 'rcvTagQty1', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'inspectedQty1', dataField: 'inspectedQty1', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'inspectedQty2', dataField: 'inspectedQty2', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'inspectedQty3', dataField: 'inspectedQty3', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'priceBuy', dataField: 'priceBuy', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'priceWholeSale', dataField: 'priceWholeSale', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'priceSale', dataField: 'priceSale', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'icDate', dataField: 'icDate', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'orderKey', dataField: 'orderKey', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'orderLineNo', dataField: 'orderLineNo', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'ownerOrderNo', dataField: 'ownerOrderNo', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'ownerOrderLineNo', dataField: 'ownerOrderLineNo', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'custOrderNo', dataField: 'custOrderNo', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'custOrderLineNo', dataField: 'custOrderLineNo', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'orderType', dataField: 'orderType', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'rcvQtyErrorFlg', dataField: 'rcvQtyErrorFlg', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'logicFlg1', dataField: 'logicFlg1', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'logicFlg2', dataField: 'logicFlg2', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'logicFlg3', dataField: 'logicFlg3', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'moveLineNo', dataField: 'moveLineNo', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'assyLineNo', dataField: 'assyLineNo', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'produceLineNo', dataField: 'produceLineNo', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'checkLastLotFlg', dataField: 'checkLastLotFlg', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'remarks', dataField: 'remarks', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'xdockFreeQty1', dataField: 'xdockFreeQty1', width: 200, fixed: false, visible: true, allowEditing: true },
        { caption: 'xdockFlg', dataField: 'xdockFlg', width: 200, fixed: false, visible: true, allowEditing: true },
    ];
}


